/*
  Copyright (c) 2026 Blue Astra Technologies LLP, India. All Rights Reserved.
  Proprietary software. Unauthorized copying or use by any means or technology
  (including AI tools) is strictly prohibited.
*/
/* =====================================================
   TOKEN VAULT — encrypt/decrypt OAuth tokens at rest.

   - When KMS_KEY_ID (+ an EC2 IAM role / AWS creds) is configured: AWS KMS
     ENVELOPE encryption. A unique data key per token is generated by KMS, used to
     AES-256-GCM the token, and only the KMS-wrapped data key is stored. The master
     key never leaves KMS. Stored as "kms:<edk>.<iv>.<tag>.<ct>".
   - Otherwise: application AES-256-GCM using ENCRYPTION_KEY (utils/encryption).
     Stored as "app:<iv:tag:ct>".

   Ciphertext is self-describing (prefix), so we can roll forward to KMS without a
   migration — old rows keep decrypting. The @aws-sdk/client-kms import is lazy, so
   it is only required when KMS is actually enabled.
   ===================================================== */
const crypto = require('crypto');
const { encrypt: appEncrypt, decrypt: appDecrypt } = require('./encryption');

let _kms = null;
function kms() {
  if (!_kms) {
    const { KMSClient } = require('@aws-sdk/client-kms');
    _kms = new KMSClient({ region: process.env.AWS_REGION || 'eu-north-1' });
  }
  return _kms;
}

const kmsEnabled = () => !!process.env.KMS_KEY_ID;

async function encryptToken(plaintext) {
  if (plaintext == null || plaintext === '') return null;
  if (kmsEnabled()) {
    const { GenerateDataKeyCommand } = require('@aws-sdk/client-kms');
    const dk = await kms().send(new GenerateDataKeyCommand({ KeyId: process.env.KMS_KEY_ID, KeySpec: 'AES_256' }));
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', Buffer.from(dk.Plaintext), iv);
    const ct = Buffer.concat([cipher.update(String(plaintext), 'utf8'), cipher.final()]);
    const tag = cipher.getAuthTag();
    return 'kms:' + [
      Buffer.from(dk.CiphertextBlob).toString('base64'),
      iv.toString('base64'),
      tag.toString('base64'),
      ct.toString('base64')
    ].join('.');
  }
  return 'app:' + appEncrypt(String(plaintext));
}

async function decryptToken(stored) {
  if (!stored) return null;
  if (stored.startsWith('kms:')) {
    const [edk, iv, tag, ct] = stored.slice(4).split('.');
    const { DecryptCommand } = require('@aws-sdk/client-kms');
    const dk = await kms().send(new DecryptCommand({ CiphertextBlob: Buffer.from(edk, 'base64') }));
    const decipher = crypto.createDecipheriv('aes-256-gcm', Buffer.from(dk.Plaintext), Buffer.from(iv, 'base64'));
    decipher.setAuthTag(Buffer.from(tag, 'base64'));
    return Buffer.concat([decipher.update(Buffer.from(ct, 'base64')), decipher.final()]).toString('utf8');
  }
  if (stored.startsWith('app:')) return appDecrypt(stored.slice(4));
  return appDecrypt(stored); // legacy (no prefix)
}

module.exports = { encryptToken, decryptToken, kmsEnabled };
